server:
  port: ${PORT:8080}

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

external:
  wallex:
    base-api-url: https://api.wallex.ir

  nobitex:
    base-api-url: https://apiv2.nobitex.ir

  bot:
    token:
    base-api-url: https://tapi.bale.ai/bot${external.bot.token}

scheduler:
  arbitrage:
    enabled: true
    interval-secs: 20

service:
  arbitrage:
    supported-currencies:
      - BTC
      - ETH
      - USDT
    subscription-token:
  command:
    handler-registry:
      base-package: com.mahdy.cryptoarbitrage.api.handler

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: crypto-arbitrage
